defaults: &defaults
  adapter: mysql
  username: root
  password:
  host: localhost

development:
  database: datamapper_on_rails3_development
  <<: *defaults

test:
  database: datamapper_on_rails3_test
  <<: *defaults

production:
  database: datamapper_on_rails3_production
  <<: *defaults
